# Dicionário para normalizar nomes de livros da Bíblia
livros_biblia = {
    "Gênesis": ["genesis", "gênesis", "gen"],
    "Êxodo": ["êxodo", "exodo", "exo"],
    "Levítico": ["levítico", "levitico", "lev"],
    "Números": ["números", "numeros", "num"],
    "Deuteronômio": ["deuteronômio", "deuteronomio", "deut"],
    "Josué": ["josué", "josue", "jos"],
    "Juízes": ["juízes", "juizes", "jz"],
    "Rute": ["rute", "rut", "rt"],
    "1 Samuel": ["1 samuel", "primeiro samuel", "primeira samuel", "1 sam", "1sm", "1samuel"],
    "2 Samuel": ["2 samuel", "segundo samuel", "segunda samuel", "2 sam", "2sm", "2samuel"],
    "1 Reis": ["1 reis", "primeiro reis", "primeira reis", "1 rs", "1rs", "1reis"],
    "2 Reis": ["2 reis", "segundo reis", "segunda reis", "2 rs", "2rs", "2reis"],
    "1 Crônicas": ["1 crônicas", "primeira crônicas", "primeiro crônicas", "1 cron", "1cr", "1crônicas", "1cronicas"],
    "2 Crônicas": ["2 crônicas", "segunda crônicas", "segundo crônicas", "2 cron", "2cr", "2crônicas", "2cronicas"],
    "Esdras": ["esdras", "esd"],
    "Neemias": ["neemias", "nee"],
    "Ester": ["ester", "est"],
    "Jó": ["jó", "jo"],
    "Salmos": ["salmos", "salmo", "sl"],
    "Provérbios": ["provérbios", "provérbio", "proverbios", "pv"],
    "Eclesiastes": ["eclesiastes", "ecle", "ecl"],
    "Cânticos": ["cânticos", "cant", "ct"],
    "Isaías": ["isaías", "isaias", "is"],
    "Jeremias": ["jeremias", "jer"],
    "Lamentações": ["lamentações", "lamentacoes", "lm"],
    "Ezequiel": ["ezequiel", "ezeq", "ez"],
    "Daniel": ["daniel", "dan"],
    "Oséias": ["oséias", "oseias", "os"],
    "Joel": ["joel", "jl"],
    "Amós": ["amós", "amos", "am"],
    "Obadias": ["obadias", "obd"],
    "Jonas": ["jonas", "jon"],
    "Miquéias": ["miquéias", "miqueias", "mic"],
    "Naum": ["naum", "na"],
    "Habacuque": ["habacuque", "hab"],
    "Sofonias": ["sofonias", "sof"],
    "Ageu": ["ageu", "Ageu", "ag"],
    "Zacarias": ["zacarias", "zac"],
    "Malaquias": ["malaquias", "mal"],
    "Mateus": ["mateus", "mat"],
    "Marcos": ["marcos", "mc"],
    "Lucas": ["lucas", "luc"],
    "Joao": ["joão", "joao", "jo"],
    "Atos": ["atos", "at"],
    "Romanos": ["romanos", "rom"],
    "1 Coríntios": ["1 coríntios", "Coríntios", "primeira coríntios", "primeiro coríntios", "1 cor", "1co", "1corintios", '1º Coríntios'],
    "2 Coríntios": ["2 coríntios", "segunda coríntios", "segundo coríntios", "2 cor", "2co", "2corintios", '2º Coríntios'],
    '1 Samuel': ['1 Samuel', 'Primeiro Samuel', 'Primeira Samuel', '1º Samuel'],
    '2 Samuel': ['2 Samuel', 'Segundo Samuel', 'Segunda Samuel', '2º Samuel'],
    "Gálatas": ["gálatas", "galatas", "gl"],
    "Efesios": ["efésios", "efesios", "ef"],
    "Filipenses": ["filipenses", "flp"],
    "Colossenses": ["colossenses", "col"],
    "1 Tessalonicenses": ["1 tessalonicenses", "primeira tessalonicenses", "primeiro tessalonicenses", "1 tes", "1ts"],
    "2 Tessalonicenses": ["2 tessalonicenses", "segunda tessalonicenses", "segundo tessalonicenses", "2 tes", "2ts"],
    "1 Timóteo": ["1 timóteo", "timóteo", "primeira timóteo", "primeiro timóteo", "1 tim", "1tm", "1timoteo"],
    "2 Timóteo": ["2 timóteo", "segunda timóteo", "segundo timóteo", "2 tim", "2tm", "2timoteo"],
    "Tito": ["tito", "tt"],
    "Filemom": ["filemom", "fm"],
    "Hebreus": ["hebreus", "heb"],
    "Tiago": ["tiago", "tg"],
    "1 Pedro": ["1 pedro", "primeira pedro", "primeiro pedro", "1 pe", "1pd", "1pedro"],
    "2 Pedro": ["2 pedro", "segunda pedro", "segundo pedro", "2 pe", "2pd", "2pedro"],
    "1 Joao": ["1 joão", "primeira joão", "primeiro joão", "1 jo", "1jo", "1joao"],
    "2 Joao": ["2 joão", "segunda joão", "segundo joão", "2 jo", "2jo", "2joao"],
    "3 Joao": ["3 joão", "terceira joão", "terceiro joão", "3 jo", "3jo", "3joao"],
    "Judas": ["judas", "jd"],
    "Apocalipse": ["apocalipse", "apo", "ap"]
}

# Dicionário para converter números por extenso em números
numeros_por_extenso = {
    "um": "1", "dois": "2", "três": "3", "quatro": "4", "cinco": "5",
    "seis": "6", "sete": "7", "oito": "8", "nove": "9", "dez": "10",
    "onze": "11", "doze": "12", "treze": "13", "catorze": "14", "quinze": "15",
    "dezesseis": "16", "dezessete": "17", "dezoito": "18", "dezenove": "19",
    "vinte": "20", "vinte e um": "21", "vinte e dois": "22", "vinte e três": "23",
    "vinte e quatro": "24", "vinte e cinco": "25", "vinte e seis": "26", 
    "vinte e sete": "27", "vinte e oito": "28", "vinte e nove": "29", 
    "trinta": "30", "trinta e um": "31", "trinta e dois": "32", 
    "trinta e três": "33", "trinta e quatro": "34", "trinta e cinco": "35", 
    "trinta e seis": "36", "trinta e sete": "37", "trinta e oito": "38", 
    "trinta e nove": "39", "quarenta": "40", "quarenta e um": "41", 
    "quarenta e dois": "42", "quarenta e três": "43", "quarenta e quatro": "44", 
    "quarenta e cinco": "45", "quarenta e seis": "46", "quarenta e sete": "47", 
    "quarenta e oito": "48", "quarenta e nove": "49", "cinquenta": "50", 
    "cinquenta e um": "51", "cinquenta e dois": "52", "cinquenta e três": "53", 
    "cinquenta e quatro": "54", "cinquenta e cinco": "55", "cinquenta e seis": "56", 
    "cinquenta e sete": "57", "cinquenta e oito": "58", "cinquenta e nove": "59", 
    "sessenta": "60", "sessenta e um": "61", "sessenta e dois": "62", 
    "sessenta e três": "63", "sessenta e quatro": "64", "sessenta e cinco": "65", 
    "sessenta e seis": "66", "sessenta e sete": "67", "sessenta e oito": "68", 
    "sessenta e nove": "69", "setenta": "70", "setenta e um": "71", 
    "setenta e dois": "72", "setenta e três": "73", "setenta e quatro": "74", 
    "setenta e cinco": "75", "setenta e seis": "76", "setenta e sete": "77", 
    "setenta e oito": "78", "setenta e nove": "79", "oitenta": "80", 
    "oitenta e um": "81", "oitenta e dois": "82", "oitenta e três": "83", 
    "oitenta e quatro": "84", "oitenta e cinco": "85", "oitenta e seis": "86", 
    "oitenta e sete": "87", "oitenta e oito": "88", "oitenta e nove": "89", 
    "noventa": "90", "noventa e um": "91", "noventa e dois": "92", 
    "noventa e três": "93", "noventa e quatro": "94", "noventa e cinco": "95", 
    "noventa e seis": "96", "noventa e sete": "97", "noventa e oito": "98", 
    "noventa e nove": "99", "cem": "100", "cento e um": "101", "cento e dois": "102", 
    "cento e três": "103", "cento e quatro": "104", "cento e cinco": "105", 
    "cento e seis": "106", "cento e sete": "107", "cento e oito": "108", 
    "cento e nove": "109", "cento e dez": "110", "cento e onze": "111", 
    "cento e doze": "112", "cento e treze": "113", "cento e quatorze": "114", 
    "cento e quinze": "115", "cento e dezesseis": "116", "cento e dezessete": "117", 
    "cento e dezoito": "118", "cento e dezenove": "119", "cento e vinte": "120", 
    "cento e vinte e um": "121", "cento e vinte e dois": "122", "cento e vinte e três": "123", 
    "cento e vinte e quatro": "124", "cento e vinte e cinco": "125", 
    "cento e vinte e seis": "126", "cento e vinte e sete": "127", "cento e vinte e oito": "128", 
    "cento e vinte e nove": "129", "cento e trinta": "130", "cento e trinta e um": "131", 
    "cento e trinta e dois": "132", "cento e trinta e três": "133", "cento e trinta e quatro": "134", 
    "cento e trinta e cinco": "135", "cento e trinta e seis": "136", "cento e trinta e sete": "137", 
    "cento e trinta e oito": "138", "cento e trinta e nove": "139", "cento e quarenta": "140", 
    "cento e quarenta e um": "141", "cento e quarenta e dois": "142", "cento e quarenta e três": "143", 
    "cento e quarenta e quatro": "144", "cento e quarenta e cinco": "145", "cento e quarenta e seis": "146", 
    "cento e quarenta e sete": "147", "cento e quarenta e oito": "148", "cento e quarenta e nove": "149", 
    "cento e cinquenta": "150",    
    # Números ordinais
    'primeiro': '1',
    'primeira': '1',
    'segundo': '2',
    'segunda': '2',
    'terceiro': '3',
    'terceira': '3'
}